# task 2 - Superstore_USA
1 . load this data in sql and in pandas with a relation in sql

2 . while loading this data you dont have to create a table manually you can use any automated approach to create a table and load a data in bulk in table

3 . Find out how return that we ahve recived and with a product id

4 . try  to join order and return data both in sql and pandas

5 . Try to find out how many unique customer that we have

6 . try to find out in how many regions we are selling a product and who is a manager for a respective region

7 . find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset

8 . Create a new coulmn and try to find our a diffrence between order date and shipment date

9 . base on question number 8 find out for which order id we have shipment duration more than 10 days

10 . Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well

11 . Gorup by region and find out which region is more profitable

12 . Try to find out overalll in which country we are giving more didscount

13 . Give me a list of unique postal code

14 . which customer segement is more profitalble find it out.

15 . try to find out the 10th most loss making product catagory.

16 . Try to find out 10 top  product with highest margins

submit your git link for the same 
 
you have to submit this task by next Friday 5th 11PM IST  to respective mail id 
sudhanshu@ineuron.ai , sunny.savita@ineuron.ai

In [1]:
import pandas as pd
import mysql.connector as conn
from sqlalchemy import engine

In [2]:
mysql_settings = {
    "user":"root",
    "passwd":"th1nk11t",
}
mysql = conn.Connect(**mysql_settings)
cursor = mysql.cursor()
cursor.execute("USE liveclasstask31july")

## 1 . load this data in sql and in pandas with a relation in sql

In [3]:
# Reading All the Sheets in one go
df = pd.read_excel('Superstore_USA.xlsx',sheet_name=None)

In [4]:
# we got a dictionary with key as sheet name and Dataframe as its value
df.keys()

dict_keys(['Orders', 'Returns', 'Users'])

In [5]:
# Creating DataFrame from dictionary
df_orders = df['Orders']
df_returns = df['Returns']
df_users = df['Users']

In [6]:
df_orders

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [7]:
df_returns

      Order ID    Status
0           65  Returned
1          612  Returned
2          614  Returned
3          678  Returned
4          710  Returned
...        ...       ...
1629    182681  Returned
1630    182683  Returned
1631    182750  Returned
1632    182781  Returned
1633    182906  Returned

[1634 rows x 2 columns]

In [8]:
df_users

    Region  Manager
0  Central    Chris
1     East     Erin
2    South      Sam
3     West  William

#### NOT ABLE TO FIND ANY WAY TO CREATE RELATIONAL SCHEMA in MySql

## 2 . while loading this data you dont have to create a table manually you can use any automated approach to create a table and load a data in bulk in table

In [9]:
mysql_engin = engine.create_engine("mysql+pymysql://root:th1nk11t@localhost/liveclasstask31july")
df_orders.to_sql('orders',index=False,con=mysql_engin)
df_returns.to_sql('returns',index=False,con=mysql_engin)
df_users.to_sql('users',index=False,con=mysql_engin)

4

## 3 . Find out how many return that we have recived and with a product id

In [10]:
df_returns.merge(df_orders)[['Order ID','Product Name']]

    Order ID                                       Product Name
0        612                                         Xerox 1928
1        612                                               6190
2       4610  80 Minute Slim Jewel Case CD-R , 10/Pack - Sta...
3       4610         #10 White Business Envelopes,4 1/8 x 9 1/2
4       7079  Hon 2090 “Pillow Soft” Series Mid Back Swivel/...
..       ...                                                ...
93     57638  Chromcraft Bull-Nose Wood Round Conference Tab...
94     57638       Personal Creations™ Ink Jet Cards and Labels
95     57638  Kleencut® Forged Office Shears by Acme United ...
96     59009                                          Xerox 197
97     59937                                          Xerox 197

[98 rows x 2 columns]

In [11]:
query = "SELECT orders.`Order ID`,`Product Name` FROM orders JOIN returns ON orders.`Order ID` = returns.`Order ID`"
cursor.execute(query)
dict(cursor.fetchall())

{9895: 'Dixon My First Ticonderoga Pencil, #2',
 13959: 'EcoTones® Memo Sheets',
 36038: 'Newell 35',
 39490: 'Hon Non-Folding Utility Tables',
 37760: 'Accessory34',
 37414: 'Chromcraft Bull-Nose Wood 48" x 96" Rectangular Conference Tables',
 47265: 'Xerox 1983',
 7079: 'Eureka Recycled Copy Paper 8 1/2" x 11", Ream',
 8353: 'Imation 3.5 IBM Formatted Diskettes, 10/Box',
 17155: 'Fellowes Neat Ideas® Storage Cubes',
 48487: 'Mead 1st Gear 2" Zipper Binder, Asst. Colors',
 55968: 'Crayola Anti Dust Chalk, 12/Pack',
 56452: 'Chromcraft Rectangular Conference Tables',
 26784: 'Sharp EL500L Fraction Calculator',
 57638: 'Kleencut® Forged Office Shears by Acme United Corporation',
 50246: 'Xerox 210',
 51559: 'Boston 1799 Powerhouse™ Electric Pencil Sharpener',
 47813: 'Xerox 1923',
 31303: 'Avery Hanging File Binders',
 56931: 'Bell Sonecor JB700 Caller ID',
 17985: 'Accessory39',
 24519: 'Pressboard Data Binder, Crimson, 12" X 8 1/2"',
 54914: 'Eldon Simplefile® Box Office®',
 33477: 'Avery 503',
 54595: 'Acme® Elite Stainless Steel Scissors',
 15009: 'Staples #10 Colored Envelopes',
 55874: 'Staples Standard Envelopes',
 41760: '600 Series Flip',
 53285: 'GBC DocuBind P100 Manual Binding Machine',
 22656: 'Belkin ErgoBoard™ Keyboard',
 49762: 'Prang Colored Pencils',
 15303: 'Imation IBM Formatted Diskettes, 100/Pack',
 37380: 'Acco Clips to Go™ Binder Clips, 24 Clips in Two Sizes',
 49027: 'Executive Impressions 12" Wall Clock',
 54563: 'DAX Metal Frame, Desktop, Stepped-Edge',
 37250: 'Tyvek ® Top-Opening Peel & Seel ® Envelopes, Gray',
 50721: 'Ibico Hi-Tech Manual Binding System',
 20036: 'Micro Innovations Micro 3000 Keyboard, Black',
 59937: 'Xerox 197',
 13984: 'Tenex Carpeted, Granite-Look or Clear Contemporary Contour Shape Chair Mats',
 12900: 'Okidata ML184 Turbo Dot Matrix Printers',
 36743: 'Master Giant Foot® Doorstop, Safety Yellow',
 41059: 'Bretford CR8500 Series Meeting Room Furniture',
 7364: 'Brown Kraft Recycled Envelopes',
 13284: 'Vinyl Sectional Post Binders',
 4610: '#10 White Business Envelopes,4 1/8 x 9 1/2',
 43713: '12 Colored Short Pencils',
 46375: '232',
 11425: 'CF 688',
 13444: 'Wirebound Voice Message Log Book',
 37924: 'Model L Table or Wall-Mount Pencil Sharpener',
 22787: 'Bagged Rubber Bands',
 45794: 'Zoom V.92 V.44 PCI Internal Controllerless FaxModem',
 7203: 'GBC DocuBind TL300 Electric Binding System',
 59009: 'Xerox 197',
 32931: 'Eldon Simplefile® Box Office®',
 612: '6190',
 7107: 'Recycled Steel Personal File for Standard File Folders',
 42823: 'Xerox 1980',
 13638: 'TDK 4.7GB DVD+RW',
 47109: 'SAFCO Folding Chair Trolley'}

## 4 . try  to join order and return data both in sql and pandas

In [12]:
# All the Oders which got the return request are merged on the basis of "Order ID" because this is the only
# Common Column in both the dataframe
df_returns.merge(df_orders)

,Order ID,Status,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,...,Product Base Margin,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales
0,612,Returned,95,Medium,0.10,5.28,6.26,3011,Tammy Raynor,Regular Air,...,0.40,East,Massachusetts,Boston,2113,2013-10-20,2013-10-22,-166.290000,105,552.03
1,612,Returned,96,Medium,0.01,65.99,2.50,3011,Tammy Raynor,Regular Air,...,0.55,East,Massachusetts,Boston,2113,2013-10-20,2013-10-22,881.676000,90,5297.63
2,4610,Returned,653,Low,0.09,8.33,1.99,2548,Wayne Bass,Regular Air,...,0.52,West,California,Los Angeles,90068,2011-06-17,2011-06-19,-17.010000,12,100.32
3,4610,Returned,654,Low,0.08,15.67,1.39,2548,Wayne Bass,Regular Air,...,0.38,West,California,Los Angeles,90068,2011-06-17,2011-06-21,203.010000,44,678.72
4,7079,Returned,979,Medium,0.01,280.98,57.00,478,Michael Wiggins,Delivery Truck,...,0.78,East,New York,New York City,10177,2011-02-08,2011-02-09,-416.700000,44,12296.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,57638,Returned,8079,Low,0.09,217.85,29.10,699,Jenny Gold,Delivery Truck,...,0.68,West,California,Los Angeles,90041,2013-04-22,2013-04-27,-526.478095,35,5740.62
94,57638,Returned,8080,Low,0.07,11.48,5.43,699,Jenny Gold,Regular Air,...,0.36,West,California,Los Angeles,90041,2013-04-22,2013-04-24,78.890000,49,570.43
95,57638,Returned,8081,Low,0.08,2.08,2.56,699,Jenny Gold,Regular Air,...,0.55,West,California,Los Angeles,90041,2013-04-22,2013-04-24,-85.580000,49,100.08
96,59009,Returned,8251,Critical,0.02,30.98,17.08,2882,Andrew Gonzalez,Express Air,...,0.40,South,North Carolina,Charlotte,28206,2012-11-18,2012-11-20,-9.336600,65,2103.64
97,59937,Returned,8389,High,0.02,30.98,17.08,1733,Nina Horne Kelly,Regular Air,...,0.40,East,District of Columbia,Washington,20012,2010-12-28,2010-12-29,-32.280000,13,438.25

In [13]:
query = "SELECT * FROM orders JOIN returns ON orders.`Order ID` = returns.`Order ID`"
cursor.execute(query)
cursor.fetchall()

[(1359,
  'Low',
  0.05,
  5.85,
  2.27,
  21,
  'Tony Wilkins Winters',
  'Regular Air',
  'Small Business',
  'Office Supplies',
  'Pens & Art Supplies',
  'Wrap Bag',
  'Dixon My First Ticonderoga Pencil, #2',
  0.56,
  'East',
  'New York',
  'New York City',
  10012,
  datetime.datetime(2011, 4, 20, 0, 0),
  datetime.datetime(2011, 4, 24, 0, 0),
  -6.82,
  9,
  54.79,
  9895,
  9895,
  'Returned'),
 (1950,
  'Medium',
  0.01,
  4.91,
  0.5,
  117,
  'Linda Weiss',
  'Regular Air',
  'Home Office',
  'Office Supplies',
  'Labels',
  'Small Box',
  'Avery 493',
  0.36,
  'West',
  'Washington',
  'Seattle',
  98103,
  datetime.datetime(2010, 4, 4, 0, 0),
  datetime.datetime(2010, 4, 6, 0, 0),
  112.06,
  47,
  228.46,
  13959,
  13959,
  'Returned'),
 (1951,
  'Medium',
  0.09,
  4.0,
  1.3,
  117,
  'Linda Weiss',
  'Express Air',
  'Home Office',
  'Office Supplies',
  'Paper',
  'Wrap Bag',
  'EcoTones® Memo Sheets',
  0.37,
  'West',
  'Washington',
  'Seattle',
  98103,
  datetime.datetime(2010, 4, 4, 0, 0),
  datetime.datetime(2010, 4, 6, 0, 0),
  16.79,
  19,
  77.61,
  13959,
  13959,
  'Returned'),
 (5055,
  'High',
  0.02,
  3.28,
  5.0,
  117,
  'Linda Weiss',
  'Regular Air',
  'Home Office',
  'Office Supplies',
  'Pens & Art Supplies',
  'Wrap Bag',
  'Newell 35',
  0.56,
  'West',
  'Washington',
  'Seattle',
  98103,
  datetime.datetime(2013, 8, 16, 0, 0),
  datetime.datetime(2013, 8, 18, 0, 0),
  -89.06,
  52,
  190.52,
  36038,
  36038,
  'Returned'),
 (5573,
  'Low',
  0.02,
  11.97,
  5.81,
  272,
  'Eleanor Swain',
  'Regular Air',
  'Small Business',
  'Office Supplies',
  'Pens & Art Supplies',
  'Small Pack',
  'Staples SlimLine Pencil Sharpener',
  0.6,
  'South',
  'North Carolina',
  'Charlotte',
  28204,
  datetime.datetime(2013, 8, 12, 0, 0),
  datetime.datetime(2013, 8, 12, 0, 0),
  -81.9413,
  76,
  912.06,
  39490,
  39490,
  'Returned'),
 (5574,
  'Low',
  0.03,
  159.31,
  60.0,
  272,
  'Eleanor Swain',
  'Delivery Truck',
  'Small Business',
  'Furniture',
  'Tables',
  'Jumbo Drum',
  'Hon Non-Folding Utility Tables',
  0.55,
  'South',
  'North Carolina',
  'Charlotte',
  28204,
  datetime.datetime(2013, 8, 12, 0, 0),
  datetime.datetime(2013, 8, 16, 0, 0),
  11.034899999999999,
  34,
  5689.28,
  39490,
  39490,
  'Returned'),
 (5302,
  'High',
  0.01,
  8.33,
  1.99,
  308,
  'Glen Caldwell',
  'Regular Air',
  'Small Business',
  'Technology',
  'Computer Peripherals',
  'Small Pack',
  '80 Minute Slim Jewel Case CD-R , 10/Pack - Staples',
  0.52,
  'West',
  'Washington',
  'Seattle',
  98115,
  datetime.datetime(2010, 8, 14, 0, 0),
  datetime.datetime(2010, 8, 15, 0, 0),
  10.74,
  32,
  280.62,
  37760,
  37760,
  'Returned'),
 (5303,
  'High',
  0.04,
  85.99,
  0.99,
  308,
  'Glen Caldwell',
  'Regular Air',
  'Small Business',
  'Technology',
  'Telephones and Communication',
  'Wrap Bag',
  'Accessory34',
  0.55,
  'West',
  'Washington',
  'Seattle',
  98115,
  datetime.datetime(2013, 8, 14, 0, 0),
  datetime.datetime(2013, 8, 16, 0, 0),
  897.867,
  76,
  5546.06,
  37760,
  37760,
  'Returned'),
 (5257,
  'Low',
  0.09,
  550.98,
  64.59,
  349,
  'Kim Weiss',
  'Delivery Truck',
  'Home Office',
  'Furniture',
  'Tables',
  'Jumbo Box',
  'Chromcraft Bull-Nose Wood 48" x 96" Rectangular Conference Tables',
  0.66,
  'South',
  'Florida',
  'Miami',
  33132,
  datetime.datetime(2012, 9, 9, 0, 0),
  datetime.datetime(2012, 9, 11, 0, 0),
  -1770.9659767800001,
  76,
  40136.93,
  37414,
  37414,
  'Returned'),
 (6643,
  'Critical',
  0.02,
  5.98,
  5.46,
  349,
  'Kim Weiss',
  'Regular Air',
  'Home Office',
  'Office Supplies',
  'Paper',
  'Small Box',
  'Xerox 1983',
  0.36,
  'South',
  'Florida',
  'Miami',
  33132,
  datetime.datetime(2012, 12, 10, 0, 0),
  datetime.datetime(2012, 12, 11, 0, 0),
  -80.9039,
  62,
  374.26,
  47265,
  47265,
  'Returned'),
 (979,
  'Medium',
  0.01,
  280.98,
  57.0,
  478,
  'Michael Wiggins',
  'Delivery Truck',
  'Small Business',
  'Furniture',
  'Chairs & Chairmats',
  'Jumbo Drum',
  'Hon 2090 “Pillow Soft” Series Mid Back Swivel/Tilt Chairs',
  0.78,
  'East',
  'New York',
  'New York City',
  10177,
  datetime.datetime(2011, 2, 8, 0, 0),
  datetime.datetime(2011, 2, 9, 0, 0),
  -416.7,
  44,
  12296.49,
  7079,
  7079,
  'Returned'),
 (980,
  'Medium',
  0.03,
  6.48,
  5.94,
  478,
  'Michael Wiggins',
  'Regular Air',
  'Small Business',
  'Office Supplies',
  'Paper',
  'Small Box',
  'Eureka Recycled Copy Paper 8 1/2" x 11", Ream',
  0.37,
  'East',
  'New York',
  'New York City',
  10177,
  datetime.datetime(2011, 2, 8, 0, 0),
  datetime.datetime(2011, 2, 10, 0, 0),
  -34.91,
  18,
  128.13,
  7079,
  7079,
  'Returned'),
 (1147,
  'Medium',
  0.08,
  2.94,
  0.96,
  491,
  'Toni Swanson',
  'Regular Air',
  'Consumer',
  'Office Supplies',
  'Pens & Art Supplies',
  'Wrap Bag',
  'Newell 343',
  0.58,
  'East',
  'New York',
  'New York City',
  10154,
  datetime.datetime(2010, 5, 15, 0, 0),
  datetime.datetime(2010, 5, 17, 0, 0),
  -2.12,
  23,
  66.7,
  8353,
  8353,
  'Returned'),
 (1146,
  'Medium',
  0.06,
  8.32,
  2.38,
  491,
  'Toni Swanson',
  'Regular Air',
  'Consumer',
  'Technology',
  'Computer Peripherals',
  'Small Pack',
  'Imation 3.5 IBM Formatted Diskettes, 10/Box',
  0.74,
  'East',
  'New York',
  'New York City',
  10154,
  datetime.datetime(2013, 5, 15, 0, 0),
  datetime.datetime(2013, 5, 17, 0, 0),
  -36.63,
  44,
  371.28,
  8353,
  8353,
  'Returned'),
 (2368,
  'Medium',
  0.0,
  6.88,
  2.0,
  553,
  'Kristine Connolly',
  'Express Air',
  'Home Office',
  'Office Supplies',
  'Paper',
  'Wrap Bag',
  'Adams Phone Message Book, 200 Message Capacity, 8 1/16” x 11”',
  0.39,
  'West',
  'California',
  'Los Angeles',
  90008,
  datetime.datetime(2010, 1, 28, 0, 0),
  datetime.datetime(2010, 1, 29, 0, 0),
  34.068000000000005,
  36,
  267.53,
  17155,
  17155,
  'Returned'),
 (2369,
  'Medium',
  0.03,
  32.48,
  35.0,
  553,
  'Kristine Connolly',
  'Express Air',
  'Home Office',
  'Office Supplies',
  'Storage & Organization',
  'Large Box',
  'Fellowes Neat Ideas® Storage Cubes',
  0.81,
  'West',
  'California',
  'Los Angeles',
  90008,
  datetime.datetime(2013, 1, 28, 0, 0),
  datetime.datetime(2013, 1, 28, 0, 0),
  -1440.4319999999998,
  34,
  1168.35,
  17155,
  17155,
  'Returned'),
 (6813,
  'Low',
  0.0,
  12.97,
  1.49,
  604,
  'Lindsay P Ashley',
  'Regular Air',
  'Home Office',
  'Office Supplies',
  'Binders and Binder Accessories',
  'Small Box',
  'Mead 1st Gear 2" Zipper Binder, Asst. Colors',
  0.35,
  'West',
  'California',
  'Los Angeles',
  90045,
  datetime.datetime(2011, 1, 11, 0, 0),
  datetime.datetime(2011, 1, 13, 0, 0),
  58.46640000000001,
  27,
  360.7,
  48487,
  48487,
  'Returned'),
 (7828,
  'Low',
  0.05,
  1.82,
  1.0,
  604,
  'Lindsay P Ashley',
  'Regular Air',
  'Home Office',
  'Office Supplies',
  'Pens & Art Supplies',
  'Wrap Bag',
  'Crayola Anti Dust Chalk, 12/Pack',
  0.4,
  'West',
  'California',
  'Los Angeles',
  90045,
  datetime.datetime(2013, 9, 30, 0, 0),
  datetime.datetime(2013, 10, 2, 0, 0),
  0.86,
  84,
  154.6,
  55968,
  55968,
  'Returned'),
 (7893,
  'Not Specified',
  0.0,
  236.97,
  59.24,
  640,
  'Neal Wolfe',
  'Delivery Truck',
  'Consumer',
  'Furniture',
  'Tables',
  'Jumbo Box',
  'Chromcraft Rectangular Conference Tables',
  0.61,
  'West',
  'Washington',
  'Seattle',
  98119,
  datetime.datetime(2010, 2, 14, 0, 0),
  datetime.datetime(2010, 2, 15, 0, 0),
  1192.04,
  34,
  6686.34,
  56452,
  56452,
  'Returned'),
 (3749,
  'Critical',
  0.02,
  120.98,
  30.0,
  699,
  'Jenny Gold',
  'Delivery Truck',
  'Consumer',
  'Furniture',
  'Chairs & Chairmats',
  'Jumbo Drum',
  'Hon Every-Day® Chair Series Swivel Task Chairs',
  0.64,
  'West',
  'California',
  'Los Angeles',
  90041,
  datetime.datetime(2011, 7, 23, 0, 0),
  datetime.datetime(2011, 7, 24, 0, 0),
  -64.14,
  14,
  1711.44,
  26784,
  26784,
  'Returned'),
 (8079,
  'Low',
  0.09,
  217.85,
  29.1,
  699,
  'Jenny Gold',
  'Delivery Truck',
  'Consumer',
  'Furniture',
  'Tables',
  'Jumbo Box',
  'Chromcraft Bull-Nose Wood Round Conference Table Top, Wood Base',
  0.68,
  'West',
  'California',
  'Los Angeles',
  90041,
  datetime.datetime(2013, 4, 22, 0, 0),
  datetime.datetime(2013, 4, 27, 0, 0),
  -526.478095,
  35,
  5740.62,
  57638,
  57638,
  'Returned'),
 (8080,
  'Low',
  0.07,
  11.48,
  5.43,
  699,
  'Jenny Gold',
  'Regular Air',
  'Consumer',
  'Office Supplies',
  'Paper',
  'Small Box',
  'Personal Creations™ Ink Jet Cards and Labels',
  0.36,
  'West',
  'California',
  'Los Angeles',
  90041,
  datetime.datetime(2013, 4, 22, 0, 0),
  datetime.datetime(2013, 4, 24, 0, 0),
  78.89,
  49,
  570.43,
  57638,
  57638,
  'Returned'),
 (8081,
  'Low',
  0.08,
  2.08,
  2.56,
  699,
  'Jenny Gold',
  'Regular Air',
  'Consumer',
  'Office Supplies',
  'Scissors, Rulers and Trimmers',
  'Small Pack',
  'Kleencut® Forged Office Shears by Acme United Corporation',
  0.55,
  'West',
  'California',
  'Los Angeles',
  90041,
  datetime.datetime(2013, 4, 22, 0, 0),
  datetime.datetime(2013, 4, 24, 0, 0),
  -85.58,
  49,
  100.08,
  57638,
  57638,
  'Returned'),
 (3750,
  'Critical',
  0.09,
  13.99,
  7.51,
  699,
  'Jenny Gold',
  'Regular Air',
  'Consumer',
  'Technology',
  'Office Machines',
  'Medium Box',
  'Sharp EL500L Fraction Calculator',
  0.39,
  'West',
  'California',
  'Los Angeles',
  90041,
  datetime.datetime(2013, 7, 23, 0, 0),
  datetime.datetime(2013, 7, 24, 0, 0),
  -37.9407,
  46,
  613.65,
  26784,
  26784,
  'Returned'),
 (7038,
  'Medium',
  0.05,
  6.48,
  7.37,
  894,
  'Gail Rankin Cole',
  'Express Air',
  'Corporate',
  'Office Supplies',
  'Paper',
  'Small Box',
  'Xerox 210',
  0.37,
  'East',
  'District of Columbia',
  'Washington',
  20024,
  datetime.datetime(2011, 8, 18, 0, 0),
  datetime.datetime(2011, 8, 19, 0, 0),
  -47.67,
  25,
  182.21,
  50246,
  50246,
  'Returned'),
 (7234,
  'Low',
  0.09,
  25.98,
  4.08,
  949,
  'Ernest Oh',
  'Regular Air',
  'Consumer',
  'Office Supplies',
  'Pens & Art Supplies',
  'Small Pack',
  'Boston 1799 Powerhouse™ Electric Pencil Sharpener',
  0.57,
  'West',
  'California',
  'Los Angeles',
  90049,
  datetime.datetime(2013, 3, 4, 0, 0),
  datetime.datetime(2013, 3, 13, 0, 0),
  129.81,
  34,
  823.98,
  51559,
  51559,
  'Returned'),
 (6711,
  'High',
  0.0,
  6.68,
  5.66,
  1044,
  'Erin Ballard',
  'Regular Air',
  'Home Office',
  'Office Supplies',
  'Paper',
  'Small Box',
  'Xerox 1923',
  0.37,
  'West',
  'California',
  'Los Angeles',
  90004,
  datetime.datetime(2010, 8, 27, 0, 0),
  datetime.datetime(2010, 8, 29, 0, 0),
  -76.94,
  90,
  617.4,
  47813,
  47813,
  'Returned'),
 (4398,
  'Low',
  0.09,
  5.98,
  1.49,
  1044,
  'Erin Ballard',
  'Express Air',
  'Home Office',
  'Office Supplies',
  'Binders and Binder Accessories',
  'Small Box',
  'Avery Hanging File Binders',
  0.39,
  'West',
  'California',
  'Los Angeles',
  90004,
  datetime.datetime(2012, 3, 20, 0, 0),
  datetime.datetime(2012, 3, 22, 0, 0),
  87.601,
  56,
  342.87,
  31303,
  31303,
  'Returned'),
 (7966,
  'High',
  0.05,
  7.99,
  5.03,
  1060,
  'Gene Gilliam',
  'Regular Air',
  'Small Business',
  'Technology',
  'Telephones and Communication',
  'Medium Box',
  'Bell Sonecor JB700 Caller ID',
  0.6,
  'South',
  'Georgia',
  'Atlanta',
  30318,
  datetime.datetime(2011, 2, 3, 0, 0),
  datetime.datetime(2011, 2, 5, 0, 0),
  -147.09002,
  34,
  232.42,
  56931,
  56931,
  'Returned'),
 (2474,
  'Medium',
  0.01,
  110.98,
  30.0,
  1104,
  'Timothy Ross',
  'Delivery Truck',
  'Home Office',
  'Furniture',
  'Chairs & Chairmats',
  'Jumbo Drum',
  'Office Star Flex Back Scooter Chair with White Frame',
  0.71,
  'East',
  'New York',
  'New York City',
  10282,
  datetime.datetime(2012, 4, 12, 0, 0),
  datetime.datetime(2012, 4, 13, 0, 0),
  -183.26,
  4,
  473.88,
  17985,
  17985,
  'Returned'),
 (2475,
  'Medium',
  0.07,
  20.99,
  3.3,
  1104,
  'Timothy Ross',
  'Regular Air',
  'Home Office',
  'Technology',
  'Telephones and Communication',
  'Small Pack',
  'Accessory39',
  0.81,
  'East',
  'New York',
  'New York City',
  10282,
  datetime.datetime(2012, 4, 12, 0, 0),
  datetime.datetime(2012, 4, 14, 0, 0),
  -133.309,
  56,
  950.91,
  17985,
  17985,
  'Returned'),
 (3435,
  'Critical',
  0.03,
  5.34,
  5.63,
  1106,
  'Maxine Collier Grady',
  'Regular Air',
  'Consumer',
  'Office Supplies',
  'Binders and Binder Accessories',
  'Small Box',
  'Pressboard Data Binder, Crimson, 12" X 8 1/2"',
  0.39,
  'Central',
  'Texas',
  'Dallas',
  75220,
  datetime.datetime(2012, 6, 11, 0, 0),
  datetime.datetime(2012, 6, 12, 0, 0),
  -60.72,
  36,
  208.73,
  24519,
  24519,
  'Returned'),
 (7659,
  'Critical',
  0.06,
  5.98,
  5.46,
  1106,
  'Maxine Collier Grady',
  'Regular Air',
  'Small Business',
  'Office Supplies',
  'Paper',
  'Small Box',
  'Xerox 1983',
  0.36,
  'Central',
  'Texas',
  'Dallas',
  75220,
  datetime.datetime(2012, 8, 28, 0, 0),
  datetime.datetime(2012, 8, 29, 0, 0),
  -57.64,
  63,
  389.67,
  54914,
  54914,
  'Returned'),
 (7660,
  'Critical',
  0.06,
  12.44,
  6.27,
  1106,
  'Maxine Collier Grady',
  'Regular Air',
  'Small Business',
  'Office Supplies',
  'Storage & Organization',
  'Medium Box',
  'Eldon Simplefile® Box Office®',
  0.57,
  'Central',
  'Texas',
  'Dallas',
  75220,
  datetime.datetime(2012, 8, 28, 0, 0),
  datetime.datetime(2012, 8, 30, 0, 0),
  -27.83,
  14,
  181.16,
  54914,
  54914,
  'Returned'),
 (4697,
  'High',
  0.08,
  10.35,
  0.99,
  1106,
  'Maxine Collier Grady',
  'Regular Air',
  'Small Business',
  'Office Supplies',
  'Labels',
  'Small Box',
  'Avery 503',
  0.37,
  'Central',
  'Texas',
  'Dallas',
  75220,
  datetime.datetime(2013, 10, 19, 0, 0),
  datetime.datetime(2013, 10, 21, 0, 0),
  113.63,
  59,
  567.41,
  33477,
  33477,
  'Returned'),
 (7632,
  'Medium',
  0.09,
  130.98,
  30.0,
  1217,
  'Billy Perry Browning',
  'Delivery Truck',
  'Small Business',
  'Furniture',
  'Chairs & Chairmats',
  'Jumbo Drum',
  'Office Star - Contemporary Task Swivel chair with 2-way adjustable arms, Plum',
  0.78,
  'East',
  'Massachusetts',
  'Boston',
  2112,
  datetime.datetime(2010, 4, 28, 0, 0),
  datetime.datetime(2010, 5, 1, 0, 0),
  -421.76,
  41,
  5258.94,
  54595,
  54595,
  'Returned'),
 (2099,
  'Not Specified',
  0.09,
  28.15,
  8.99,
  1217,
  'Billy Perry Browning',
  'Express Air',
  'Small Business',
  'Office Supplies',
  'Pens & Art Supplies',
  'Small Pack',
  'Boston Electric Pencil Sharpener, Model 1818, Charcoal Black',
  0.57,
  'East',
  'Massachusetts',
  'Boston',
  2112,
  datetime.datetime(2012, 12, 21, 0, 0),
  datetime.datetime(2012, 12, 23, 0, 0),
  -7.8,
  92,
  2400.26,
  15009,
  15009,
  'Returned'),
 (2100,
  'Not Specified',
  0.08,
  7.78,
  2.5,
  1217,
  'Billy Perry Browning',
  'Express Air',
  'Small Business',
  'Office Supplies',
  'Envelopes',
  'Small Box',
  'Staples #10 Colored Envelopes',
  0.38,
  'East',
  'Massachusetts',
  'Boston',
  2112,
  datetime.datetime(2012, 12, 21, 0, 0),
  datetime.datetime(2012, 12, 22, 0, 0),
  61.09,
  56,
  458.86,
  15009,
  15009,
  'Returned'),
 (7631,
  'Medium',
  0.02,
  8.34,
  2.64,
  1217,
  'Billy Perry Browning',
  'Regular Air',
  'Small Business',
  'Office Supplies',
  'Scissors, Rulers and Trimmers',
  'Small Pack',
  'Acme® Elite Stainless Steel Scissors',
  0.59,
  'East',
  'Massachusetts',
  'Boston',
  2112,
  datetime.datetime(2013, 4, 28, 0, 0),
  datetime.datetime(2013, 4, 30, 0, 0),
  6.79,
  30,
  250.29,
  54595,
  54595,
  'Returned'),
 (7810,
  'Medium',
  0.0,
  7.1,
  6.05,
  1228,
  'Hazel Jennings',
  'Regular Air',
  'Small Business',
  'Office Supplies',
  'Binders and Binder Accessories',
  'Small Box',
  'Wilson Jones Hanging View Binder, White, 1"',
  0.39,
  'East',
  'Pennsylvania',
  'Philadelphia',
  19140,
  datetime.datetime(2010, 2, 16, 0, 0),
  datetime.datetime(2010, 2, 17, 0, 0),
  -60.145,
  28,
  208.83,
  55874,
  55874,
  'Returned'),
 (7811,
  'Medium',
  0.01,
  4.98,
  4.62,
  1228,
  'Hazel Jennings',
  'Express Air',
  'Small Business',
  'Technology',
  'Computer Peripherals',
  'Small Pack',
  'Imation 3.5", DISKETTE 44766 HGHLD3.52HD/FM, 10/Pack',
  0.64,
  'East',
  'Pennsylvania',
  'Philadelphia',
  19140,
  datetime.datetime(2010, 2, 16, 0, 0),
  datetime.datetime(2010, 2, 18, 0, 0),
  -111.72,
  41,
  228.3,
  55874,
  55874,
  'Returned'),
 (7812,
  'Medium',
  0.06,
  5.68,
  1.39,
  1228,
  'Hazel Jennings',
  'Regular Air',
  'Small Business',
  'Office Supplies',
  'Envelopes',
  'Small Box',
  'Staples Standard Envelopes',
  0.38,
  'East',
  'Pennsylvania',
  'Philadelphia',
  19140,
  datetime.datetime(2010, 2, 16, 0, 0),
  datetime.datetime(2010, 2, 16, 0, 0),
  33.01,
  24,
  129.53,
  55874,
  55874,
  'Returned'),
 (5882,
  'Low',
  0.04,
  315.98,
  19.99,
  1228,
  'Hazel Jennings',
  'Regular Air',
  'Small Business',
  'Office Supplies',
  'Binders and Binder Accessories',
  'Small Box',
  'GBC ProClick™ 150 Presentation Binding System',
  0.38,
  'East',
  'Pennsylvania',
  'Philadelphia',
  19140,
  datetime.datetime(2013, 1, 27, 0, 0),
  datetime.datetime(2013, 2, 1, 0, 0),
  1059.2326,
  23,
  7325.68,
  41760,
  41760,
  'Returned'),
 (5883,
  'Low',
  0.0,
  9.98,
  12.52,
  1228,
  'Hazel Jennings',
  'Regular Air',
  'Small Business',
  'Furniture',
  'Office Furnishings',
  'Small Box',
  'Eldon® Expressions™ Wood and Plastic Desk Accessories, Oak',
  0.57,
  'East',
  'Pennsylvania',
  'Philadelphia',
  19140,
  datetime.datetime(2013, 1, 27, 0, 0),
  datetime.datetime(2013, 2, 3, 0, 0),
  -213.08800000000002,
  24,
  269.95,
  41760,
  41760,
  'Returned'),
 (5884,
  'Low',
  0.08,
  115.99,
  2.5,
  1228,
  'Hazel Jennings',
  'Regular Air',
  'Small Business',
  'Technology',
  'Telephones and Communication',
  'Small Box',
  '6160',
  0.57,
  'East',
  'Pennsylvania',
  'Philadelphia',
  19140,
  datetime.datetime(2013, 1, 27, 0, 0),
  datetime.datetime(2013, 2, 1, 0, 0),
  -446.1952,
  8,
  783.68,
  41760,
  41760,
  'Returned'),
 (5885,
  'Low',
  0.05,
  95.99,
  8.99,
  1228,
  'Hazel Jennings',
  'Regular Air',
  'Small Business',
  'Technology',
  'Telephones and Communication',
  'Small Box',
  '600 Series Flip',
  0.57,
  'East',
  'Pennsylvania',
  'Philadelphia',
  19140,
  datetime.datetime(2013, 1, 27, 0, 0),
  datetime.datetime(2013, 2, 1, 0, 0),
  278.78040000000004,
  44,
  3555.35,
  41760,
  41760,
  'Returned'),
 (7466,
  'Critical',
  0.04,
  165.98,
  19.99,
  1246,
  'Lois Hansen',
  'Regular Air',
  'Home Office',
  'Office Supplies',
  'Binders and Binder Accessories',
  'Small Box',
  'GBC DocuBind P100 Manual Binding Machine',
  0.4,
  'East',
  'New York',
  'New York City',
  10009,
  datetime.datetime(2013, 5, 24, 0, 0),
  datetime.datetime(2013, 5, 26, 0, 0),
  163.8035,
  8,
  1390.61,
  53285,
  53285,
  'Returned'),
 (3155,
  'Not Specified',
  0.05,
  30.98,
  6.5,
  1280,
  'Harold Albright',
  'Express Air',
  'Corporate',
  'Technology',
  'Computer Peripherals',
  'Small Box',
  'Belkin ErgoBoard™ Keyboard',
  0.64,
  'West',
  'Washington',
  'Seattle',
  98119,
  datetime.datetime(2011, 12, 22, 0, 0),
  datetime.datetime(2011, 12, 24, 0, 0),
  -77.89,
  19,
  587.67,
  22656,
  22656,
  'Returned'),
 (6959,
  'High',
  0.09,
  2.94,
  0.81,
  1313,
  'Katherine Knight',
  'Regular Air',
  'Corporate',
  'Office Supplies',
  'Pens & Art Supplies',
  'Wrap Bag',
  'Prang Colored Pencils',
  0.4,
  'East',
  'Pennsylvania',
  'Philadelphia',
  19134,
  datetime.datetime(2012, 6, 15, 0, 0),
  datetime.datetime(2012, 6, 17, 0, 0),
  23.74,
  58,
  164.27,
  49762,
  49762,
  'Returned'),
 (2143,
  'Critical',
  0.02,
  4.54,
  5.83,
  1314,
  'Keith Marsh',
  'Regular Air',
  'Home Office',
  'Office Supplies',
  'Binders and Binder Accessories',
  'Small Box',

## 5 . Try to find out how many unique customer that we have

#### Here we can see there are total 2703 unique customers

In [14]:
df_orders[['Customer Name']].drop_duplicates()

        Customer Name
0     Janice Fletcher
1       Bonnie Potter
7      Ronnie Proctor
9        Dwight Hwang
13          Leon Gill
...               ...
9406    Marc McDaniel
9409      Marvin Reid
9413    Florence Gold
9420   Frederick Cole
9424    Tammy Buckley

[2703 rows x 1 columns]

In [15]:
query = "SELECT DISTINCT `Customer Name` FROM orders"
cursor.execute(query)
print(f"There are Total {len(cursor.fetchall())} unique cutomers")

There are Total 2703 unique cutomers

## 6 . try to find out in how many regions we are selling a product and who is a manager for a respective region

In [16]:
df_orders.merge(df_users)[['Region','Manager']].drop_duplicates()

       Region  Manager
0     Central    Chris
2899     West  William
5183     East     Erin
7472    South      Sam

In [17]:
query = "SELECT DISTINCT O.`Region`,U.`Manager` FROM orders O JOIN users U on O.`Region` = U.`Region`"
cursor.execute(query)
cursor.fetchall()

[('Central', 'Chris'), ('West', 'William'), ('East', 'Erin'), ('South', 'Sam')]

## 7 . find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset

In [18]:
df_orders['Ship Mode'].value_counts()/sum(df_orders['Ship Mode'].value_counts())*100

Regular Air       74.644600
Delivery Truck    13.611288
Express Air       11.744112
Name: Ship Mode, dtype: float64

## 8 . Create a new coulmn and try to find our a diffrence between order date and shipment date

In [19]:
df_orders['Shipment Duration'] = pd.to_timedelta(df_orders['Ship Date']-df_orders['Order Date'])

In [20]:
df_orders

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Shipment Duration
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525,2 days
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522,1 days
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523,1 days
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523,1 days
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523,0 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532,1 days
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532,0 days
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533,2 days
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530,3 days
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533,2 days

In [21]:
query = "ALTER TABLE orders ADD `Shipment Duration` INT"
cursor.execute(query)
query = "UPDATE orders SET `Shipment Duration` = DATEDIFF(`Ship Date`,`Order Date`)"
cursor.execute(query)
mysql.commit()

## 9 . base on question number 8 find out for which order id we have shipment duration more than 10 days

In [22]:
df_orders[df_orders['Shipment Duration']>pd.to_timedelta(10,unit='D')][['Order ID','Shipment Duration']]

      Order ID Shipment Duration
643      87215           84 days
1548     86318           11 days
1549     86318           15 days
1678     87957           17 days
1679     87957           11 days
1680     87957           28 days
1697     19556           17 days
1698     19556           11 days
1699     19556           28 days
2515     86177           92 days
5548     88223           14 days
5673     88352           17 days
5859     87572           22 days
5881     91294           24 days
8607     86434           18 days
8609     86436           17 days
8610     86436           19 days
8973     87300           19 days
8982     19841           27 days
8983     19841           31 days
8993     19841           19 days
8996     87300           27 days
8997     87300           31 days

In [23]:
query="SELECT `Order ID`,CONCAT(`Shipment Duration`,' Days') FROM orders WHERE `Shipment Duration`>10"
cursor.execute(query)
dict(cursor.fetchall())

{87215: '84 Days',
 86318: '15 Days',
 87957: '28 Days',
 19556: '28 Days',
 86177: '92 Days',
 88223: '14 Days',
 88352: '17 Days',
 87572: '22 Days',
 91294: '24 Days',
 86434: '18 Days',
 86436: '19 Days',
 87300: '31 Days',
 19841: '19 Days'}

## 10 . Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well

#### There are No Records in which we have delay in shipment more than 15 days and got returned!!

In [24]:
df_orders.merge(df_returns)[['Shipment Duration']].drop_duplicates()

   Shipment Duration
0             4 days
1             2 days
4             0 days
6             1 days
21            5 days
25            9 days
35            3 days
43            7 days

#### To Verify my code I change it to 5 days

In [25]:
# There are No Records in which we have delay in shipment more than 15 days and got returned!!
# To Verify my code I change it to 5 days
df_orders[df_orders['Shipment Duration']>pd.to_timedelta(5,unit='D')].merge(df_returns).merge(df_users)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Shipment Duration,Status,Manager
0,7234,Low,0.09,25.98,4.08,949,Ernest Oh,Regular Air,Consumer,Office Supplies,...,90049,2013-03-04,2013-03-13,129.810,34,823.98,51559,9 days,Returned,William
1,4627,Low,0.06,2.88,0.50,3004,Maurice Everett,Regular Air,Corporate,Office Supplies,...,90049,2011-02-15,2011-02-22,32.700,31,86.10,32931,7 days,Returned,William
2,5883,Low,0.00,9.98,12.52,1228,Hazel Jennings,Regular Air,Small Business,Furniture,...,19140,2013-01-27,2013-02-03,-213.088,24,269.95,41760,7 days,Returned,Erin

In [26]:
query = "SELECT * FROM orders join returns on orders.`Order ID` = returns.`Order ID` where `Shipment Duration`>5"
cursor.execute(query)
print(f"There are total {len(cursor.fetchall())} records which are delayed by more than 5 days and got return")

There are total 3 records which are delayed by more than 5 days and got return

## 11 . Gorup by region and find out which region is more profitable

In [27]:
df_orders.groupby('Region')['Profit'].mean().sort_values(ascending=False)

Region
Central    179.312027
East       164.948094
West       136.098710
South       53.327120
Name: Profit, dtype: float64

In [28]:
query = "SELECT `Region`,AVG(`Profit`) FROM orders GROUP BY `Region` ORDER BY AVG(`Profit`) DESC"
cursor.execute(query)
dict(cursor.fetchall())

{'Central': 179.31202727374978,
 'East': 164.94809351011799,
 'West': 136.09871011243447,
 'South': 53.32711996908387}

## 12 . Try to find out overalll in which country are giving more discount

In [29]:
# These are the top 5 countries giving discount
df_orders.groupby('State or Province')['Discount'].mean().sort_values(ascending=False).head()

State or Province
Wyoming         0.054762
Louisiana       0.054607
Rhode Island    0.054500
Utah            0.052534
Minnesota       0.052385
Name: Discount, dtype: float64

In [30]:
query = "SELECT `State or Province`,AVG(`Discount`) FROM orders GROUP BY `State or Province` ORDER BY AVG(`Discount`) DESC LIMIT 5"
cursor.execute(query)
dict(cursor.fetchall())

{'Wyoming': 0.05476190476190477,
 'Louisiana': 0.05460674157303368,
 'Rhode Island': 0.05450000000000001,
 'Utah': 0.05253424657534242,
 'Minnesota': 0.05238493723849366}

## 13 . Give me a list of unique postal code

In [31]:
postal_code_list = df_orders['Postal Code'].unique().tolist()
postal_code_list

[60101,
 98221,
 91776,
 95123,
 2724,
 3110,
 8101,
 8109,
 7203,
 2907,
 55372,
 11787,
 13210,
 59405,
 59601,
 59801,
 68005,
 10012,
 92653,
 92677,
 92530,
 92630,
 90712,
 93534,
 90260,
 97405,
 97526,
 97030,
 97123,
 97303,
 62002,
 98373,
 98052,
 75019,
 23834,
 62701,
 60107,
 60477,
 14150,
 12180,
 77642,
 75080,
 77471,
 78664,
 75088,
 24153,
 94043,
 92563,
 94559,
 10177,
 2917,
 5401,
 4070,
 2331,
 8830,
 8701,
 7470,
 7481,
 5201,
 97035,
 44708,
 45231,
 44105,
 95687,
 5451,
 94591,
 70056,
 22102,
 60601,
 66209,
 66215,
 66502,
 66062,
 6510,
 4401,
 4005,
 2129,
 2038,
 1852,
 1752,
 2067,
 3820,
 8618,
 7644,
 7110,
 8861,
 7095,
 2895,
 97128,
 97504,
 98103,
 84118,
 84041,
 93277,
 76903,
 78207,
 60004,
 94952,
 1510,
 1106,
 1880,
 6401,
 6360,
 2664,
 15122,
 76148,
 5439,
 5403,
 37664,
 37918,
 37086,
 37087,
 80525,
 80817,
 60452,
 76131,
 98059,
 99352,
 37804,
 70802,
 4092,
 7024,
 76240,
 98158,
 78415,
 94122,
 4011,
 4240,
 2474,
 2540,
 1580,
 3038,
 60505,
 84043,
 84321,
 66212,
 48138,
 85335,
 74006,
 75217,
 77536,
 90660,
 13501,
 11580,
 63114,
 84044,
 84047,
 84107,
 60453,
 2021,
 2766,
 7101,
 28227,
 60302,
 60462,
 50208,
 80027,
 66203,
 81503,
 80634,
 37922,
 38109,
 55423,
 55901,
 55113,
 80126,
 80232,
 17331,
 33772,
 87505,
 12208,
 44106,
 43229,
 78589,
 86001,
 85234,
 85301,
 30297,
 28204,
 6824,
 6111,
 6226,
 7109,
 66614,
 67212,
 80538,
 80233,
 80134,
 6830,
 6770,
 6855,
 4073,
 1069,
 2725,
 21234,
 21128,
 21208,
 20854,
 98115,
 91945,
 94404,
 60130,
 1007,
 7111,
 8052,
 21133,
 60510,
 3045,
 7410,
 97045,
 97206,
 44221,
 6478,
 33181,
 4101,
 3246,
 3101,
 7010,
 2878,
 33132,
 13601,
 85338,
 86401,
 19406,
 93727,
 4072,
 7628,
 7071,
 2816,
 2910,
 2886,
 94601,
 2149,
 1840,
 48234,
 37814,
 62223,
 61008,
 61701,
 60440,
 19026,
 68025,
 68801,
 68847,
 68502,
 48509,
 63105,
 13021,
 13905,
 28001,
 45406,
 43015,
 95240,
 90805,
 4901,
 8360,
 78666,
 7026,
 93405,
 94403,
 2358,
 7201,
 7032,
 7666,
 68104,
 89701,
 94583,
 92704,
 6010,
 6108,
 4330,
 1462,
 2370,
 7047,
 7480,
 61801,
 68701,
 56301,
 94024,
 93635,
 95032,
 90266,
 1923,
 2457,
 3054,
 8332,
 90069,
 92683,
 90604,
 2019,
 1915,
 2341,
 7506,
 8601,
 30318,
 1845,
 39180,
 11704,
 11795,
 60543,
 95020,
 4106,
 2062,
 7042,
 10154,
 24281,
 37130,
 84404,
 84057,
 55416,
 46041,
 42104,
 41011,
 95336,
 4038,
 2148,
 8753,
 76067,
 11226,
 97756,
 85204,
 85737,
 84062,
 64064,
 63043,
 22025,
 60061,
 93101,
 95051,
 26501,
 88201,
 78155,
 75090,
 90008,
 68046,
 84604,
 60067,
 60068,
 60087,
 60185,
 75081,
 60187,
 60090,
 39701,
 89015,
 61554,
 61604,
 91767,
 6415,
 4210,
 2032,
 1801,
 3301,
 8021,
 7031,
 7054,
 60091,
 60517,
 46016,
 47401,
 46032,
 47201,
 21136,
 81001,
 90045,
 14224,
 10605,
 10701,
 97301,
 97477,
 97224,
 81007,
 48195,
 5701,
 43952,
 20852,
 20602,
 55106,
 55378,
 95062,
 93454,
 98119,
 60544,
 62301,
 55379,
 60089,
 89115,
 91730,
 2116,
 1540,
 77373,
 37211,
 75203,
 52501,
 64133,
 63301,
 64506,
 98387,
 99207,
 98408,
 77478,
 63116,
 63376,
 80229,
 80030,
 46307,
 46312,
 98105,
 90041,
 90405,
 95404,
 95070,
 6040,
 6460,
 6850,
 6702,
 1520,
 2152,
 7067,
 2840,
 48841,
 89031,
 89041,
 41042,
 6614,
 1803,
 1420,
 1089,
 2190,
 3053,
 3079,
 7003,
 7016,
 7039,
 8232,
 7901,
 85345,
 85023,
 60423,
 40324,
 86301,
 86314,
 97062,
 61201,
 98661,
 14215,
 61107,
 97068,
 18103,
 16602,
 72143,
 92054,
 6033,
 6484,
 6437,
 92691,
 95351,
 6512,
 7001,
 73064,
 27502,
 84067,
 29915,
 84106,
 32168,
 37830,
 42420,
 85254,
 8046,
 99362,
 37167,
 37174,
 79605,
 75002,
 79109,
 71854,
 80033,
 21222,
 6511,
 8002,
 91745,
 93117,
 6114,
 2210,
 1450,
 1060,
 3839,
 92544,
 92345,
 6405,
 6810,
 6492,
 75503,
 77590,
 46514,
 55126,
 89502,
 66202,
 11575,
 85635,
 93422,
 20746,
 76017,
 78745,
 77520,
 77705,
 76021,
 89431,
 20024,
 83616,
 76201,
 33430,
 10039,
 1887,
 7652,
 42240,
 26003,
 78521,
 77803,
 76028,
 96003,
 92374,
 1463,
 7008,
 8857,
 7050,
 7501,
 90278,
 6776,
 2127,
 1605,
 7002,
 2914,
 90049,
 75482,
 75067,
 19901,
 19711,
 94061,
 60610,
 6105,
 2108,
 3842,
 92503,
 95677,
 2339,
 1841,
 7079,
 91761,
 1718,
 1701,
 1040,
 2151,
 7650,
 93030,
 3431,
 7601,
 7450,
 11720,
 60459,
 7712,
 72022,
 28806,
 27217,
 27511,
 66762,
 55125,
 15221,
 11722,
 14225,
 11725,
 27514,
 28205,
 28027,
 27707,
 43017,
 15102,
 95695,
 95991,
 92399,
 90004,
 6473,
 2109,
 7030,
 85351,
 85374,
 3060,
 2864,
 11727,
 10573,
 60409,
 62901,
 18018,
 60441,
 60174,
 60193,
 60076,
 11729,
 11746,
 8816,
 8817,
 7646,
 65721,
 10282,
 18040,
 75220,
 77566,
 75146,
 78041,
 77573,
 80004,
 85281,
 85705,
 85364,
 72714,
 72015,
 92592,
 95661,
 75116,
 78852,
 78539,
 2118,
 79907,
 76039,
 75234,
 60188,
 75056,
 77381,
 75701,
 77901,
 76706,
 75165,
 76086,
 6611,
 1821,
 1056,
 1075,
 7801,
 90640,
 1876,
 7086,
 3801,
 7407,
 8226,
 7070,
 19805,
 32701,
 2040,
 10280,
 27237,
 84660,
 84663,
 35756,
 92646,
 90301,
 6050,
 6790,
 20016,
 34142,
 1108,
 1776,
 7843,
 2920,
 32712,
 46806,
 46404,
 46530,
 97420,
 19013,
 2112,
 1906,
 2451,
 7052,
 2861,
 19140,
 98801,
 75028,
 76106,
 75007,
 75104,
 78613,
 36830,
 35020,
 78641,
 10009,
 75057,
 60110,
 61821,
 77530,
 76031,
 80013,
 80303,
 40422,
 80020,
 80104,
 80906,
 73521,
 33433,
 33437,
 34210,
 91941,
 1930,
 8401,
 7097,
 46142,
 46324,
 47591,
 19134,
 15241,
 6320,
 47274,
 1749,
 2153,
 33180,
 75601,
 84074,
 98902,
 25314,
 82604,
 84084,
 84120,
 60623,
 11554,
 90058,
 80022,
 80219,
 77840,
 2478,
 1453,
 2744,
 8302,
 8028,
 7940,
 62234,
 10170,
 17201,
 77546,
 33511,
 33063,
 33055,
 78596,
 76308,
 52761,
 48101,
 32707,
 79424,
 75901,
 76063,
 75098,
 95207,
 6408,
 2703,
 1832,
 22304,
 46342,
 46203,
 94025,
 94086,
 91360,
 1027,
 1867,
 8863,
 60653,
 48104,
 49017,
 48708,
 84003,
 92553,
 95037,
 2113,
 47130,
 46901,
 47905,
 28031,
 44112,
 80112,
 21146,
 20901,
 44035,
 44117,
 65807,
 63130,
 63135,
 16509,
 17112,
 96150,
 6795,
 2638,
 8901,
 97801,
 29687,
 46226,
 46952,
 46410,
 68601,
 84010,
 84015,
 43081,
 44145,
 44691,
 82001,
 82716,
 33134,
 53110,
 60016,
 60516,
 46360,
 10045,
 94044,
 32137,
 59901,
 14901,
 33065,
 60478,
 46544,
 47302,
 47150,
 62205,
 6488,
 6710,
 1545,
 2072,
 55305,
 35211,
 35601,
 27288,
 92262,
 63385,
 92253,
 78363,
 33314,
 32114,
 46060,
 46368,
 47374,
 39530,
 39056,
 38701,
 39503,
 22003,
 22204,
 24060,
 78501,
 75150,
 33441,
 32720,
 60123,
 45385,
 28314,
 28307,
 6607,
 77571,
 63044,
 44094,
 44511,
 25705,
 82070,
 68901,
 20601,
 11598,
 11010,
 11520,
 95823,
 93905,
 2445,
 1748,
 45324,
 46322,
 97601,
 17602,
 46375,
 11542,
 10528,
 37743,
 74012,
 77095,
 39401,
 38637,
 39212,
 92404,
 94070,
 6901,
 11714,
 60098,
 27203,
 98072,
 90503,
 15131,
 33403,
 33445,
 22015,
 22901,
 23320,
 67114,
 25801,
 45014,
 45840,
 60611,
 77301,
 60007,
 20190,
 72701,
 72903,
 71901,
 19057,
 39301,
 44118,
 19464,
 30062,
 30907,
 30265,
 49534,
 27529,
 35473,
 72401,
 72209,
 92037,
 43026,
 45424,
 44240,
 45429,
 83843,
 88310,
 20012,
 11550,
 28052,
 27534,
 27405,
 27834,
 75034,
 30305,
 73034,
 73703,
 73505,
 73110,
 90036,
 79701,
 95376,
 1607,
 32725,
 34698,
 63141,
 60126,
 60201,
 61032,
 32780,
 46614,
 47802,
 46383,
 47906,
 50010,
 92672,
 92105,
 1945,
 30188,
 59102,
 61401,
 60137,
 94110,
 50021,
 52722,
 63119,
 26101,
 36330,
 90032,
 38654,
 39208,
 48187,
 49236,
 48126,
 48127,
 33178,
 11801,
 52601,
 50613,
 52402,
 15146,
 38671,
 1810,
 2334,
 1469,
 43230,
 1886,
 11741,
 35630,
 92008,
 6443,
 2110,
 1826,
 2035,
 2169,
 1550,
 1570,
 7080,
 7090,
 2808,
 87105,
 94306,
 22193,
 24541,
 ...]

In [32]:
print(f"Total Number of unique postal code {len(postal_code_list)}")

Total Number of unique postal code 1697

In [33]:
query = "SELECT DISTINCT `Postal Code` FROM orders"
cursor.execute(query)
all_postal_code = cursor.fetchall()
print('TOTAL LENGTH OF LIST ',len(all_postal_code))
print(all_postal_code) # get all the postal code

TOTAL LENGTH OF LIST  1697
[(60101,), (98221,), (91776,), (95123,), (2724,), (3110,), (8101,), (8109,), (7203,), (2907,), (55372,), (11787,), (13210,), (59405,), (59601,), (59801,), (68005,), (10012,), (92653,), (92677,), (92530,), (92630,), (90712,), (93534,), (90260,), (97405,), (97526,), (97030,), (97123,), (97303,), (62002,), (98373,), (98052,), (75019,), (23834,), (62701,), (60107,), (60477,), (14150,), (12180,), (77642,), (75080,), (77471,), (78664,), (75088,), (24153,), (94043,), (92563,), (94559,), (10177,), (2917,), (5401,), (4070,), (2331,), (8830,), (8701,), (7470,), (7481,), (5201,), (97035,), (44708,), (45231,), (44105,), (95687,), (5451,), (94591,), (70056,), (22102,), (60601,), (66209,), (66215,), (66502,), (66062,), (6510,), (4401,), (4005,), (2129,), (2038,), (1852,), (1752,), (2067,), (3820,), (8618,), (7644,), (7110,), (8861,), (7095,), (2895,), (97128,), (97504,), (98103,), (84118,), (84041,), (93277,), (76903,), (78207,), (60004,), (94952,), (1510,), (1106,), (1880,), (6401,), (6360,), (2664,), (15122,), (76148,), (5439,), (5403,), (37664,), (37918,), (37086,), (37087,), (80525,), (80817,), (60452,), (76131,), (98059,), (99352,), (37804,), (70802,), (4092,), (7024,), (76240,), (98158,), (78415,), (94122,), (4011,), (4240,), (2474,), (2540,), (1580,), (3038,), (60505,), (84043,), (84321,), (66212,), (48138,), (85335,), (74006,), (75217,), (77536,), (90660,), (13501,), (11580,), (63114,), (84044,), (84047,), (84107,), (60453,), (2021,), (2766,), (7101,), (28227,), (60302,), (60462,), (50208,), (80027,), (66203,), (81503,), (80634,), (37922,), (38109,), (55423,), (55901,), (55113,), (80126,), (80232,), (17331,), (33772,), (87505,), (12208,), (44106,), (43229,), (78589,), (86001,), (85234,), (85301,), (30297,), (28204,), (6824,), (6111,), (6226,), (7109,), (66614,), (67212,), (80538,), (80233,), (80134,), (6830,), (6770,), (6855,), (4073,), (1069,), (2725,), (21234,), (21128,), (21208,), (20854,), (98115,), (91945,), (94404,), (60130,), (1007,), (7111,), (8052,), (21133,), (60510,), (3045,), (7410,), (97045,), (97206,), (44221,), (6478,), (33181,), (4101,), (3246,), (3101,), (7010,), (2878,), (33132,), (13601,), (85338,), (86401,), (19406,), (93727,), (4072,), (7628,), (7071,), (2816,), (2910,), (2886,), (94601,), (2149,), (1840,), (48234,), (37814,), (62223,), (61008,), (61701,), (60440,), (19026,), (68025,), (68801,), (68847,), (68502,), (48509,), (63105,), (13021,), (13905,), (28001,), (45406,), (43015,), (95240,), (90805,), (4901,), (8360,), (78666,), (7026,), (93405,), (94403,), (2358,), (7201,), (7032,), (7666,), (68104,), (89701,), (94583,), (92704,), (6010,), (6108,), (4330,), (1462,), (2370,), (7047,), (7480,), (61801,), (68701,), (56301,), (94024,), (93635,), (95032,), (90266,), (1923,), (2457,), (3054,), (8332,), (90069,), (92683,), (90604,), (2019,), (1915,), (2341,), (7506,), (8601,), (30318,), (1845,), (39180,), (11704,), (11795,), (60543,), (95020,), (4106,), (2062,), (7042,), (10154,), (24281,), (37130,), (84404,), (84057,), (55416,), (46041,), (42104,), (41011,), (95336,), (4038,), (2148,), (8753,), (76067,), (11226,), (97756,), (85204,), (85737,), (84062,), (64064,), (63043,), (22025,), (60061,), (93101,), (95051,), (26501,), (88201,), (78155,), (75090,), (90008,), (68046,), (84604,), (60067,), (60068,), (60087,), (60185,), (75081,), (60187,), (60090,), (39701,), (89015,), (61554,), (61604,), (91767,), (6415,), (4210,), (2032,), (1801,), (3301,), (8021,), (7031,), (7054,), (60091,), (60517,), (46016,), (47401,), (46032,), (47201,), (21136,), (81001,), (90045,), (14224,), (10605,), (10701,), (97301,), (97477,), (97224,), (81007,), (48195,), (5701,), (43952,), (20852,), (20602,), (55106,), (55378,), (95062,), (93454,), (98119,), (60544,), (62301,), (55379,), (60089,), (89115,), (91730,), (2116,), (1540,), (77373,), (37211,), (75203,), (52501,), (64133,), (63301,), (64506,), (98387,), (99207,), (98408,), (77478,), (63116,), (63376,), (80229,), (80030,), (46307,), (46312,), (98105,), (90041,), (90405,), (95404,), (95070,), (6040,), (6460,), (6850,), (6702,), (1520,), (2152,), (7067,), (2840,), (48841,), (89031,), (89041,), (41042,), (6614,), (1803,), (1420,), (1089,), (2190,), (3053,), (3079,), (7003,), (7016,), (7039,), (8232,), (7901,), (85345,), (85023,), (60423,), (40324,), (86301,), (86314,), (97062,), (61201,), (98661,), (14215,), (61107,), (97068,), (18103,), (16602,), (72143,), (92054,), (6033,), (6484,), (6437,), (92691,), (95351,), (6512,), (7001,), (73064,), (27502,), (84067,), (29915,), (84106,), (32168,), (37830,), (42420,), (85254,), (8046,), (99362,), (37167,), (37174,), (79605,), (75002,), (79109,), (71854,), (80033,), (21222,), (6511,), (8002,), (91745,), (93117,), (6114,), (2210,), (1450,), (1060,), (3839,), (92544,), (92345,), (6405,), (6810,), (6492,), (75503,), (77590,), (46514,), (55126,), (89502,), (66202,), (11575,), (85635,), (93422,), (20746,), (76017,), (78745,), (77520,), (77705,), (76021,), (89431,), (20024,), (83616,), (76201,), (33430,), (10039,), (1887,), (7652,), (42240,), (26003,), (78521,), (77803,), (76028,), (96003,), (92374,), (1463,), (7008,), (8857,), (7050,), (7501,), (90278,), (6776,), (2127,), (1605,), (7002,), (2914,), (90049,), (75482,), (75067,), (19901,), (19711,), (94061,), (60610,), (6105,), (2108,), (3842,), (92503,), (95677,), (2339,), (1841,), (7079,), (91761,), (1718,), (1701,), (1040,), (2151,), (7650,), (93030,), (3431,), (7601,), (7450,), (11720,), (60459,), (7712,), (72022,), (28806,), (27217,), (27511,), (66762,), (55125,), (15221,), (11722,), (14225,), (11725,), (27514,), (28205,), (28027,), (27707,), (43017,), (15102,), (95695,), (95991,), (92399,), (90004,), (6473,), (2109,), (7030,), (85351,), (85374,), (3060,), (2864,), (11727,), (10573,), (60409,), (62901,), (18018,), (60441,), (60174,), (60193,), (60076,), (11729,), (11746,), (8816,), (8817,), (7646,), (65721,), (10282,), (18040,), (75220,), (77566,), (75146,), (78041,), (77573,), (80004,), (85281,), (85705,), (85364,), (72714,), (72015,), (92592,), (95661,), (75116,), (78852,), (78539,), (2118,), (79907,), (76039,), (75234,), (60188,), (75056,), (77381,), (75701,), (77901,), (76706,), (75165,), (76086,), (6611,), (1821,), (1056,), (1075,), (7801,), (90640,), (1876,), (7086,), (3801,), (7407,), (8226,), (7070,), (19805,), (32701,), (2040,), (10280,), (27237,), (84660,), (84663,), (35756,), (92646,), (90301,), (6050,), (6790,), (20016,), (34142,), (1108,), (1776,), (7843,), (2920,), (32712,), (46806,), (46404,), (46530,), (97420,), (19013,), (2112,), (1906,), (2451,), (7052,), (2861,), (19140,), (98801,), (75028,), (76106,), (75007,), (75104,), (78613,), (36830,), (35020,), (78641,), (10009,), (75057,), (60110,), (61821,), (77530,), (76031,), (80013,), (80303,), (40422,), (80020,), (80104,), (80906,), (73521,), (33433,), (33437,), (34210,), (91941,), (1930,), (8401,), (7097,), (46142,), (46324,), (47591,), (19134,), (15241,), (6320,), (47274,), (1749,), (2153,), (33180,), (75601,), (84074,), (98902,), (25314,), (82604,), (84084,), (84120,), (60623,), (11554,), (90058,), (80022,), (80219,), (77840,), (2478,), (1453,), (2744,), (8302,), (8028,), (7940,), (62234,), (10170,), (17201,), (77546,), (33511,), (33063,), (33055,), (78596,), (76308,), (52761,), (48101,), (32707,), (79424,), (75901,), (76063,), (75098,), (95207,), (6408,), (2703,), (1832,), (22304,), (46342,), (46203,), (94025,), (94086,), (91360,), (1027,), (1867,), (8863,), (60653,), (48104,), (49017,), (48708,), (84003,), (92553,), (95037,), (2113,), (47130,), (46901,), (47905,), (28031,), (44112,), (80112,), (21146,), (20901,), (44035,), (44117,), (65807,), (63130,), (63135,), (16509,), (17112,), (96150,), (6795,), (2638,), (8901,), (97801,), (29687,), (46226,), (46952,), (46410,), (68601,), (84010,), (84015,), (43081,), (44145,), (44691,), (82001,), (82716,), (33134,), (53110,), (60016,), (60516,), (46360,), (10045,), (94044,), (32137,), (59901,), (14901,), (33065,), (60478,), (46544,), (47302,), (47150,), (62205,), (6488,), (6710,), (1545,), (2072,), (55305,), (35211,), (35601,), (27288,), (92262,), (63385,), (92253,), (78363,), (33314,), (32114,), (46060,), (46368,), (47374,), (39530,), (39056,), (38701,), (39503,), (22003,), (22204,), (24060,), (78501,), (75150,), (33441,), (32720,), (60123,), (45385,), (28314,), (28307,), (6607,), (77571,), (63044,), (44094,), (44511,), (25705,), (82070,), (68901,), (20601,), (11598,), (11010,), (11520,), (95823,), (93905,), (2445,), (1748,), (45324,), (46322,), (97601,), (17602,), (46375,), (11542,), (10528,), (37743,), (74012,), (77095,), (39401,), (38637,), (39212,), (92404,), (94070,), (6901,), (11714,), (60098,), (27203,), (98072,), (90503,), (15131,), (33403,), (33445,), (22015,), (22901,), (23320,), (67114,), (25801,), (45014,), (45840,), (60611,), (77301,), (60007,), (20190,), (72701,), (72903,), (71901,), (19057,), (39301,), (44118,), (19464,), (30062,), (30907,), (30265,), (49534,), (27529,), (35473,), (72401,), (72209,), (92037,), (43026,), (45424,), (44240,), (45429,), (83843,), (88310,), (20012,), (11550,), (28052,), (27534,), (27405,), (27834,), (75034,), (30305,), (73034,), (73703,), (73505,), (73110,), (90036,), (79701,), (95376,), (1607,), (32725,), (34698,), (63141,), (60126,), (60201,), (61032,), (32780,), (46614,), (47802,), (46383,), (47906,), (50010,), (92672,), (92105,), (1945,), (30188,), (59102,), (61401,), (60137,), (94110,), (50021,), (52722,), (63119,), (26101,), (36330,), (90032,), (38654,), (39208,), (48187,), (49236,), (48126,), (48127,), (33178,), (11801,), (52601,), (50613,), (52402,), (15146,), (38671,), (1810,), (2334,), (1469,), (43230,), (1886,), (11741,), (35630,), (92008,), (6443,), (2110,), (1826,), (2035,), (2169,), (1550,), (1570,), (7080,), (7090,), (2808,), (87105,), (94306,), (22193,), (24541,), (1519,), (7036,), (7055,), (2806,), (14217,), (43130,), (45801,), (54915,), (1028,), (2186,), (44052,), (44903,), (30269,), (95969,), (72113,), (72450,), (71603,), (91104,), (6030,), (2351,), (29611,), (29651,), (28601,), (75043,), (78626,), (75051,), (76051,), (66801,), (84020,), (72756,), (15228,), (59715,), (59750,), (55066,), (35160,), (33916,), (48066,), (48073,), (48601,), (48080,), (49455,), (52732,), (12047,), (38801,), (19090,), (48227,), (48823,), (80122,), (80501,), (84117,), (84037,), (43302,), (45040,), (11758,), (77070,), (23666,), (22801,), (81301,), (48034,), (48310,), (51503,), (19401,), (15235,), (19143,), (15239,), (79072,), (48021,), (44017,), (53005,), (75401,), (32174,), (32765,), (32905,), (10550,), (28352,), (44646,), (67901,), (69101,), (57006,), (24501,), (88220,), (27260,), (23111,), (23602,), (28079,), (41075,), (48336,), (48505,), (48135,), (65203,), (3051,), (14853,), (44236,), (72801,), (47362,), (10956,), (10801,), (35904,), (95928,), (29464,), (29577,), (29406,), (29730,), (52803,), (50315,), (52001,), (63129,), (28540,), (28081,), (28110,), (23518,), (22124,), (76117,), (76543,), (72116,), (72762,), (72301,), (2324,), (63031,), (64118,), (63042,), (64055,), (88101,), (33407,), (53094,), (20151,), (33311,), (40214,), (40356,), (48180,), (48098,), (48093,), (48329,), (48185,), (49509,), (55124,), (16146,), (2532,), (2026,), (2018,), (7011,), (42301,), (91911,), (1721,), (1013,), (1610,), (2852,), (55434,), (65109,), (28115,), (28560,), (14701,), (11756,), (11757,), (55420,), (55429,), (55445,), (55337,), (50501,), (52240,), (30337,), (20814,), (20715,), (21228,), (77015,), (44256,), (34787,), (87401,), (88240,), (19087,), (95610,), (91711,), (2048,), (33801,), (19120,), (34639,), (11561,), (19601,), (18504,), (16801,), (18705,), (42003,), (27604,), (27801,), (30161,), (30076,), (64804,), (64130,), (63122,), (39560,), (29662,), (78550,), (77036,), (14304,), (14120,), (15601,), (54703,), (53713,), (53132,), (29301,), (29483,), (55433,), (55016,), (2456,), (7017,), (7040,), (34683,), (32404,), (10011,), (57201,), (53150,), (33971,), (6374,), (92236,), (1440,), (2420,), (52302,), (54302,), (53220,), (53545,), (20735,), (20740,), (60139,), (60025,), (40258,), (40475,), (71301,), (21044,), (21114,), (21501,), (21040,), (82901,), (33917,), (34982,), (32259,), (77340,), (33024,), (55803,), (55122,), (55343,), (60031,), (49505,), (49423,), (10024,), (88001,), (87124,), (11572,), (30328,), (31401,), (60103,), (52241,), (92804,), (94509,), (60699,), (2718,), (7960,), (60035,), (60194,), (60432,), (6074,), (23805,), (23701,), (23223,), (76053,), (75061,), (76248,), (44107,), (76541,), (73160,), (20004,), (32935,), (32953,), (33142,), (1938,), (55410,), (53142,), (35209,), (35244,), (35810,), (36608,), (55014,), (55432,), (10035,), (71111,), (49783,), (28144,), (27360,), (27587,), (60901,), (30080,), (30458,), (70364,), (70065,), (70506,), (33881,), (30084,), (72023,), (94521,), (92627,), (6457,), (1913,), (7205,), (92024,), (60102,), (46321,), (77489,), (94015,), (2111,), (2138,), (7631,), (7740,), (2863,), (2908,), (75109,), (36203,), (70601,), (92307,), (2492,), (32789,), (32708,), (10580,), (24017,), (22153,), (23434,), (23464,), (90068,), (43213,), (17403,), (54601,), (53711,), (54220,), (44060,), (10562,), (11803,), (55076,), (98144,), (94526,), (95616,), (10165,), (36116,), (36801,), (36869,), (36067,), (35401,), (48141,), (49201,), (53051,), (53209,), (31707,), (30605,), (6450,), (7621,), (8871,), (2184,), (2777,), (49002,), (57401,), (10004,), (57103,), (38134,), (37027,), (28403,), (74403,), (73071,), (73120,), (74055,), (22601,), (31088,), (83704,), (33023,), (83701,), (74601,), (93309,), (15234,), (67037,), (30904,), (31907,), (30721,), (2471,), (8865,), (7076,), (46350,), (57701,), (37620,), (26301,), (98002,), (22980,), (72956,), (33952,), (35216,), (85323,), (86442,), (85704,), (83501,), (32503,), (32808,), (33566,), (60131,), (21042,), (21221,), (49001,), (49508,), (48911,), (60438,), (30135,), (37421,), (37042,), (98006,), (98226,), (98011,), (98310,), (94568,), (6241,), (1757,), (83605,), (48146,), (48154,), (85224,), (10115,), (29801,), (70072,), (33317,), (34759,), (48205,), (6708,), (2050,), (2891,), (30338,), (30344,), (20877,), (27893,), (58501,), (97071,), (74801,), (74074,), (70003,), (48071,), (48640,), (50158,), (50401,), (51106,), (90022,), (1901,), (1950,), (7083,), (37311,), (45042,), (43055,), (71203,), (92020,), (92243,), (33161,), (55044,), (56001,), (74133,), (97321,), (33160,), (21061,), (21740,), (38017,), (38401,), (79762,), (98146,), (98198,), (98026,), (32601,), (62040,), (67601,), (68128,), (75460,), (77506,), (98208,), (98023,), (98027,), (33012,), (44070,), (98107,), (34287,), (28206,), (44039,), (44133,), (44134,), (43068,), (55369,), (30809,), (30501,), (44125,), (58103,), (58201,), (58701,), (50322,), (50701,), (50265,), (33021,), (60603,), (20707,), (29624,), (29418,), (95630,), (2215,), (2719,), (2345,), (2180,), (48858,), (14043,), (98042,), (43123,), (55119,), (55407,), (54956,), (21220,), (43050,), (33030,), (32216,), (53151,), (53154,), (54901,), (58601,), (44870,), (45503,), (55345,), (67801,), (67846,), (53402,), (53081,), (49442,), (48375,), (48237,), (48342,), (48060,), (83814,), (83402,), (56560,), (14609,), (13440,), (2145,), (7065,), (10583,), (99336,), (98031,), (97007,), (97005,), (97701,), (60148,), (58554,), (97330,), (67501,), (66104,), (66044,), (66048,), (94704,), (42071,), (1742,), (2740,), (1095,), (98034,), (98503,), (44312,), (44515,), (55128,), (72712,), (72032,), (90061,), (44224,), (44136,), (43615,), (19112,), (34239,), (16148,), (33334,), (12306,), (45011,), (11967,), (34761,), (83642,), (83686,), (77041,), (83201,), (83854,), (70560,), (70117,), (32839,), (10013,), (60160,), (61265,), (60056,), (71109,), (70458,), (60060,), (60540,), (61761,), (77581,), (78660,), (78577,), (83440,), (92277,), (34769,), (33710,), (32771,), (48183,), (75023,), (33068,), (32004,), (32127,), (34952,), (6903,), (33458,), (55060,), (55441,), (33569,), (54481,), (53590,), (34609,), (94109,), (60062,), (92025,), (95501,), (83301,), (90210,), (37064,), (37066,), (31313,), (33322,), (32303,), (38138,), (37075,), (54880,), (53186,), (54401,), (94513,), (91505,), (7701,), (21403,), (20906,), (10112,), (33319,), (98632,), (98037,), (98270,), (49221,), (45431,), (94533,), (2364,), (7060,), (36701,), (11703,), (98273,), (98502,), (98444,), (29203,), (29501,), (33156,), (34741,), (20170,), (95746,), (7094,), (33404,), (33411,), (33461,), (18201,), (1001,), (1301,), (1760,), (2563,), (1890,), (8873,), (38301,), (37604,), (48239,), (21113,), (33614,), (97060,), (20006,), (48307,), (99301,), (99163,), (92231,), (93010,), (53213,), (53214,), (53095,), (21215,), (45373,), (43221,), (44483,), (20832,), (21117,), (30144,), (30240,), (31204,), (44512,), (43402,), (6820,), (60014,), (61832,), (62521,), (26554,)]

## 14 . which customer segement is more profitalble find it out.

In [34]:
df_orders.groupby('Customer Segment')['Profit'].mean().sort_values(ascending=False).head(1)

Customer Segment
Small Business    171.903635
Name: Profit, dtype: float64

In [35]:
query = """select `Customer Segment`,AVG(`Profit`) FROM orders GROUP BY `Customer Segment` ORDER BY AVG(`Profit`) DESC LIMIT 1"""
cursor.execute(query)
dict(cursor.fetchall())

{'Small Business': 171.9036352426148}

## 15 . try to find out the 10th most loss making product catagory.

In [36]:
cursor.execute("USE liveclasstask31july")

In [37]:
query = """select distinct o.SC,o.MP 
from (
		select `Product Category` AS C,
			   `Product Sub-Category` AS SC,
			    AVG(`Profit`) over(partition by `Product Sub-Category`) AS MP 
		from orders) as o 
order by o.MP limit 10
"""
query = query.replace('\n','').replace('\t','')
query

'select distinct o.SC,o.MP from (select `Product Category` AS C,   `Product Sub-Category` AS SC,    AVG(`Profit`) over(partition by `Product Sub-Category`) AS MP from orders) as o order by o.MP limit 10'

In [38]:
cursor.execute(query)
dict(cursor.fetchall())

{'Tables': -179.44322246225246,
 'Bookcases': -37.421109533980605,
 'Rubber Bands': -14.57293568923077,
 'Scissors, Rulers and Trimmers': -12.495800774193548,
 'Pens & Art Supplies': 1.6586724546463256,
 'Storage & Organization': 13.243942175081951,
 'Paper': 25.64294542248006,
 'Labels': 54.0283298024316,
 'Computer Peripherals': 103.92179966028354,
 'Office Furnishings': 104.42720936217444}

## 16 . Try to find out 10 top  product with highest margins

In [39]:
df_orders.sort_values(by=['Product Base Margin'],ascending=False)[['Product Name','Product Base Margin']].drop_duplicates().head(10)

                                           Product Name  Product Base Margin
9145                                        Accessory27                 0.85
4756                                         Accessory4                 0.85
4168                  Sterling Rubber Bands by Alliance                 0.85
3994  Office Impressions Heavy Duty Welded Shelving ...                 0.85
230                    Belkin OmniView SE Rackmount Kit                 0.85
2847  Serrated Blade or Curved Handle Hand Letter Op...                 0.84
2879                        Tennsco Commercial Shelving                 0.84
9283  Tennsco Stur-D-Stor Boltless Shelving, 5 Shelv...                 0.84
165                  Iris® 3-Drawer Stacking Bin, Black                 0.83
1539                  *Staples* vLetter Openers, 2/Pack                 0.83

In [40]:
query = """select distinct `Product Name`,`Product Base Margin` from orders order by `Product Base Margin` desc,`Product Name` ASC limit 10"""
cursor.execute(query)
dict(cursor.fetchall())

{'Accessory27': 0.85,
 'Accessory4': 0.85,
 'Belkin OmniView SE Rackmount Kit': 0.85,
 'Office Impressions Heavy Duty Welded Shelving & Multimedia Storage Drawers': 0.85,
 'Sterling Rubber Bands by Alliance': 0.85,
 'Serrated Blade or Curved Handle Hand Letter Openers': 0.84,
 'Tennsco Commercial Shelving': 0.84,
 'Tennsco Stur-D-Stor Boltless Shelving, 5 Shelves, 24" Deep, Sand': 0.84,
 '*Staples* vLetter Openers, 2/Pack': 0.83,
 'Accessory15': 0.83}